# https://cirrus-ci.org/examples/

# https://cirrus-ci.org/guide/writing-tasks/
# They have a docker_builder and a compute_engine_instance

task:
  name: dummy
  container:
    image: oilshell/soil-dummy
  # based on .builds/dummy.yml
  run_script: |
    # cd oil
    soil/worker.sh job-main dummy
    # Try it outside
    # soil/host-shim.sh mount-perms $PWD
    # soil/host-shim.sh run-job-uke podman $PWD dummy
    # soil/sourcehut.sh publish-html-assuming-ssh-key
