# https://docs.travis-ci.com/user/reference/xenial/#python-support
# It says Xenial has Python 2.7, 3.6, and 3.7 (?)
# We're not using language: python because that creates a virtualenv, which is
# specific to a Python version.  MyPy needs both in the same environment.

dist: xenial
cache: pip

# Enable this to quickly test the deploy step at the end
env:
    - TRAVIS_SKIP=''

addons:
    apt:
        packages:
            # build/dev.sh ubuntu-deps
            - python-dev
            - gawk
            - time
            - libreadline-dev
            # test/spec.sh install-shells
            - busybox-static
            - mksh
            - zsh
              # since we're not using language: python
            - python3-setuptools
            - python-pip
            - python3-pip

before_install:
    - test/spec.sh link-busybox-ash

install:
    - pip install --user flake8 typing
    # MyPy requires Python 3, but Oil requires Python 2.
    - pip3 install --user mypy
    # hack for cmark
    - build/dev.sh minimal

script:
    - services/toil-worker.sh run-dev-minimal

notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down

# from https://docs.travis-ci.com/user/deployment/script/
deploy:
    # https://docs.travis-ci.com/user/deployment#uploading-files-and-skip_cleanup
    # otherwise we can't zip up _tmp/toil, etc.
    - provider: script
      skip_cleanup: true
      script: services/travis.sh publish-html
      on:
          branch: master
    # duplicate block for testing on dev/andy-21
    - provider: script
      skip_cleanup: true
      script: services/travis.sh publish-html
      on:
          branch: dev/andy-21
