# https://docs.travis-ci.com/user/reference/xenial/#python-support
# It says Xenial has Python 2.7, 3.6, and 3.7 (?)
# We're not using language: python because that creates a virtualenv, which is
# specific to a Python version.  MyPy needs both in the same environment.

dist: xenial
cache: pip

# Enable this to quickly test the deploy step at the end
env:
    - TRAVIS_SKIP=''

addons:
    apt:
        packages:
            # build/dev.sh ubuntu-deps
            - python-dev
            - gawk
            - time
            - libreadline-dev
            # test/spec.sh install-shells
            - busybox-static
            - mksh
            - zsh
              # since we're not using language: python
            - python3-setuptools
            - python-pip
            - python3-pip

before_install:
    - test/spec.sh link-busybox-ash

install:
    - pip install --user flake8 typing
    # mypy requires Python 3
    - pip3 install --user mypy
    # hack for cmark
    - build/dev.sh minimal

script:
    - test/lint.sh travis
    # Type checking with MyPy.  Problem: mypy requires Python 3, but Oil
    # requires Python 2.  The Travis environment doesn't like that.
    - types/run.sh travis
    - types/oil-slice.sh travis
    - test/unit.sh travis
    - test/spec.sh travis

notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down

# from https://docs.travis-ci.com/user/deployment/script/
deploy:
    # deploy develop to the staging environment
    - provider: script
      script: services/travis.sh publish-html
      on:
          branch: master
          #branch: dev/andy-21
