# Soil wrapped in Github Actions.

name: oil
on: [push]
jobs:
  dummy_orig:
    runs-on: ubuntu-latest
    # container: oilshell/soil-dummy
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: dummy
        run: |
          cd $REPO_ROOT
          soil/worker.sh run-dummy

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html

  dummy:
    runs-on: ubuntu-20.04
    # container: oilshell/soil-dummy
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: dummy
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT dummy

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html

  dev-minimal:
    # https://github.com/actions/virtual-environments
    # there's no python-pip on ubuntu-latest?
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: dev-minimal
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job docker $REPO_ROOT dev-minimal

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html

  other-tests:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: other-tests
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job docker $REPO_ROOT other-tests

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html

  ovm-tarball:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: ovm-tarball
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT ovm-tarball

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html

  cpp:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: cpp
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job docker $REPO_ROOT cpp

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html
