# Soil wrapped in Github Actions.

name: oil
on: [push]
jobs:
  dummy_orig:
    runs-on: ubuntu-latest
    # container: oilshell/soil-dummy
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: dummy
        run: |
          cd $REPO_ROOT
          soil/worker.sh run-dummy

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html

  dummy:
    runs-on: ubuntu-20.04
    # container: oilshell/soil-dummy
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: dummy
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT dummy

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html dummy

  dev-minimal:
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: dev-minimal
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT dev-minimal

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html dev-minimal

  pea:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: pea
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT pea

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html pea

  other-tests:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: other-tests
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT other-tests

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html other-tests

  ovm-tarball:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: ovm-tarball
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT ovm-tarball

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html ovm-tarball

  app-tests:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: app-tests
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT app-tests

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html app-tests

  cpp:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: cpp
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT cpp

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html cpp

  maybe-merge-to-master:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    needs: [dummy, dev-minimal, cpp, ovm-tarball, pea, other-tests, app-tests]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: maybe-merge
        run: |
          cd $REPO_ROOT
          soil/worker.sh run-maybe-merge

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          # NOTE: does not publish to status API
          cd $REPO_ROOT
          soil/github-actions.sh publish-html
