# Soil wrapped in Github Actions.

name: oil
on:
  # don't run CI on master because we test soil-staging and auto-merge.
  push:
    branches-ignore:
      - master
  pull_request_target:
    branches: [master, soil-staging]
jobs:
  dummy_orig:
    runs-on: ubuntu-latest
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: dummy
        run: |
          soil/worker.sh JOB-dummy

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          # NOTE: does not publish to status API
          soil/github-actions.sh publish-and-exit dummy

  dummy:
    runs-on: ubuntu-20.04
    # container: oilshell/soil-dummy
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: dummy
        run: |
          soil/github-actions.sh run-job dummy

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          soil/github-actions.sh publish-and-exit dummy T

  dev-minimal:
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: dev-minimal
        run: |
          soil/github-actions.sh run-job dev-minimal

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          soil/github-actions.sh publish-and-exit dev-minimal T

  pea:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: pea
        run: |
          soil/github-actions.sh run-job pea

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          soil/github-actions.sh publish-and-exit pea T

  other-tests:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: other-tests
        run: |
          soil/github-actions.sh run-job other-tests

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          soil/github-actions.sh publish-and-exit other-tests T

  ovm-tarball:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: ovm-tarball
        run: |
          soil/github-actions.sh run-job ovm-tarball

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          soil/github-actions.sh publish-and-exit ovm-tarball T

  app-tests:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: app-tests
        run: |
          soil/github-actions.sh run-job app-tests

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          soil/github-actions.sh publish-and-exit app-tests T

  cpp-coverage:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: cpp-coverage
        run: |
          soil/github-actions.sh run-job cpp-coverage

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          soil/github-actions.sh publish-and-exit cpp-coverage T

  cpp-small:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: cpp-small
        run: |
          soil/github-actions.sh run-job cpp-small

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          soil/github-actions.sh publish-and-exit cpp-small T

  cpp-spec:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: cpp-spec
        run: |
          soil/github-actions.sh run-job cpp-spec

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          soil/github-actions.sh publish-and-exit cpp-spec T

  maybe-merge-to-master:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    # List of tasks to wait on.  Copied from soil/worker.sh list-jobs
    needs: ['dummy', 'dev-minimal', 'cpp-coverage', 'cpp-small', 'cpp-spec', 'ovm-tarball', 'pea', 'other-tests', 'app-tests']
    #needs: ['dummy', 'pea', 'other-tests']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: maybe-merge
        env:
          SOIL_GITHUB_API_TOKEN: ${{ secrets.SOIL_GITHUB_API_TOKEN }}
        run: |
          soil/worker.sh JOB-maybe-merge

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          # NOTE: does not publish to status API
          soil/github-actions.sh publish-and-exit maybe-merge
