# Soil wrapped in Github Actions.

name: oil
on:
  # don't run CI on master because we test soil-staging and auto-merge.
  push:
    branches-ignore:
      - master
jobs:
  dummy_orig:
    runs-on: ubuntu-latest
    # container: oilshell/soil-dummy
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: dummy
        run: |
          cd $REPO_ROOT
          soil/worker.sh JOB-dummy

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html

  dummy:
    runs-on: ubuntu-20.04
    # container: oilshell/soil-dummy
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: dummy
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT dummy

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html dummy

  dev-minimal:
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: dev-minimal
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT dev-minimal

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html dev-minimal

  pea:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: pea
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT pea

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html pea

  other-tests:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: other-tests
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT other-tests

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html other-tests

  ovm-tarball:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: ovm-tarball
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT ovm-tarball

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html ovm-tarball

  app-tests:
    runs-on: ubuntu-20.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: app-tests
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT app-tests

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html app-tests

  cpp-coverage:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: cpp-small
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT cpp-coverage

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html cpp-coverage

  cpp-small:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: cpp-small
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT cpp-small

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html cpp-small

  cpp-spec:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: mount-perms
        run: |
          soil/host-shim.sh mount-perms $REPO_ROOT

      - name: cpp-spec
        run: |
          cd $REPO_ROOT
          soil/host-shim.sh run-job-uke docker $REPO_ROOT cpp-spec

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          soil/github-actions.sh publish-html cpp-spec

  maybe-merge-to-master:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    # List of tasks to wait on.  Copied from soil/worker.sh list-jobs
    needs: ['dummy', 'dev-minimal', 'cpp-coverage', 'cpp-small', 'cpp-spec', 'ovm-tarball', 'pea', 'other-tests', 'app-tests']
    #needs: ['dummy', 'pea', 'other-tests']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: maybe-merge
        env:
          SOIL_GITHUB_API_TOKEN: ${{ secrets.SOIL_GITHUB_API_TOKEN }}
        run: |
          cd $REPO_ROOT
          soil/worker.sh JOB-maybe-merge

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          # NOTE: does not publish to status API
          cd $REPO_ROOT
          soil/github-actions.sh publish-html
