name: oil
on: [push]
jobs:
  dev-minimal:
    runs-on: ubuntu-latest
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: install
        run: |
          pip install --user flake8 typing
          # MyPy requires Python 3, but Oil requires Python 2.
          pip3 install --user mypy

          cd $REPO_ROOT
          # After this symlink is made, build/dev-shell.sh will modify $PATH to include it
          test/spec.sh link-busybox-ash

      - name: dev-minimal
        run: |
          cd $REPO_ROOT
          services/toil-worker.sh run-dev-minimal

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          services/github-actions.sh publish-html

  dummy:
    runs-on: ubuntu-latest
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: dummy
        run: |
          cd $REPO_ROOT
          services/toil-worker.sh run-dummy

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          services/github-actions.sh publish-html

  other-tests:
    runs-on: ubuntu-latest
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: other-tests
        run: |
          cd $REPO_ROOT
          services/toil-worker.sh run-other-tests

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          services/github-actions.sh publish-html

  cpp:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: 'cpp'
        run: |
          echo 'cpp'
