# Toil wrapped in Github Actions.

name: oil
on: [push]
jobs:
  dummy:
    runs-on: ubuntu-latest
    container: oilshell/toil-dummy
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: dummy
        run: |
          cd $REPO_ROOT
          services/toil-worker.sh run-dummy

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          services/github-actions.sh publish-html

  dev-minimal:
    # https://github.com/actions/virtual-environments
    # there's no python-pip on ubuntu-latest?
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install
        run: |
          build/dev.sh ubuntu-deps

          build/dev.sh install-py2  # flake8, etc.
          build/dev.sh install-py3  # MyPy

      - name: dev-minimal
        run: |
          cd $REPO_ROOT
          services/toil-worker.sh run-dev-minimal

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          services/github-actions.sh publish-html

  other-tests:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install
        run: |
          # this is an overapproximation
          build/dev.sh ubuntu-deps

      - name: other-tests
        run: |
          cd $REPO_ROOT
          services/toil-worker.sh run-other-tests

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          services/github-actions.sh publish-html

  ovm-tarball:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install
        run: |
          # this is an overapproximation
          build/dev.sh ubuntu-deps
          build/dev.sh install-py2  # flake8, etc.
          build/dev.sh install-py3  # MyPy

      - name: ovm-tarball
        run: |
          cd $REPO_ROOT
          services/toil-worker.sh run-ovm-tarball

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          services/github-actions.sh publish-html

  cpp:
    runs-on: ubuntu-18.04
    env:
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install
        run: |
          # this is an overapproximation
          build/dev.sh ubuntu-deps
          build/dev.sh install-py2  # flake8, etc.
          build/dev.sh install-py3  # MyPy

      - name: cpp
        run: |
          cd $REPO_ROOT
          services/toil-worker.sh run-cpp

      - name: publish-html
        env:
          # for deploying to dashboard
          TOIL_KEY: ${{ secrets.TOIL_KEY }}
        run: |
          cd $REPO_ROOT
          services/github-actions.sh publish-html
